In [418]:
import pandas as pd
import numpy as np
import math
import random
import statistics
import os
import glob

In [419]:
def sign(x):
    if (x>0):
        print(x,'positif')
    elif x == 0:
        print(x,'null')
    else:
        print(x,'negetif')

In [420]:
for i in range (10,-10,-1):
    sign(i)

10 positif
9 positif
8 positif
7 positif
6 positif
5 positif
4 positif
3 positif
2 positif
1 positif
0 null
-1 negetif
-2 negetif
-3 negetif
-4 negetif
-5 negetif
-6 negetif
-7 negetif
-8 negetif
-9 negetif


In [421]:
x=0
while x<10:
    print(x)
    x+=1

0
1
2
3
4
5
6
7
8
9


In [422]:
def e_potentielle_limite(masse,hauteur,limite,g=9.81):
    E= masse* hauteur* g
    print(E)
    return E<limite

In [423]:
e_potentielle_limite(50,10,6000)

4905.0


True

In [424]:
def fibonacci(n):
    a=0
    b=1
    Fib=[a]
    while a<n:
        a,b=b,a+b
        Fib.append(a)
    return Fib
print(fibonacci(1000))

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597]


In [425]:
villes=['Paris','Madrid','Amsterdam','Berlin','Londres','Bruxelles','Rome']
if 'Belfast' in villes:
    print('oui')
else:
    print('non')

non


In [426]:
for index,i in enumerate(villes):
    print(index,i)

0 Paris
1 Madrid
2 Amsterdam
3 Berlin
4 Londres
5 Bruxelles
6 Rome


In [427]:
liste_2=[0,10,20,30,40,50]
for a,b in zip(villes,liste_2):
    print(a,b)

Paris 0
Madrid 10
Amsterdam 20
Berlin 30
Londres 40
Bruxelles 50


In [428]:
liste_3=[]
for i in range(10):
    liste_3.append(i**2)
print(liste_3)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [429]:
liste_4=[i**2 for i in range(10)]
liste_4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [430]:
liste_5=[[i for i in range(2)]for j in range(3)]
liste_5

[[0, 1], [0, 1], [0, 1]]

In [431]:
dictionnaire={'0':'Pierre',
              '1':'Jean',
              '2':'Julie',
              '3':'Sophie'}

In [432]:
prenoms=['Pierre','Jean','Julie','Sophie']

In [433]:
dico={k:v for k,v in enumerate(prenoms)}
print(dico)

{0: 'Pierre', 1: 'Jean', 2: 'Julie', 3: 'Sophie'}


In [434]:
dico.values()

dict_values(['Pierre', 'Jean', 'Julie', 'Sophie'])

In [435]:
ages=[24,62,10,23]

In [436]:
dico_2={prenom:age for prenom,age in zip(prenoms, ages) if age>30}
dico_2

{'Jean': 62}

##TUPLE

In [437]:
tuple_1=tuple((i**2 for i in range(10)))
tuple_1

(0, 1, 4, 9, 16, 25, 36, 49, 64, 81)

EXERCICES

In [438]:
classeur={
    "positif":[],
    "negatif":[],
}

In [439]:
def trier(classeur,nombre):
    if nombre>=0:
        classeur['positif'].append(nombre)
    else:
        classeur['negatif'].append(nombre)
    return classeur
        

In [440]:
trier(classeur,-2)

{'positif': [], 'negatif': [-2]}

In [441]:
tuple_3=tuple((k**2 for k in range(20)))
dico3={k:v for k,v in enumerate(tuple_3)}
print(dico3)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361}


In [442]:
x=30
ville='Paris'
message="La température est de {} degC à {}".format(x,ville)
print(message)


La température est de 30 degC à Paris


In [443]:
f=open('fichier.txt','w')

In [444]:
f.write('bonjour')
f.close()

In [445]:
f=open('fichier.txt','r')
print(f.read())
f.close()

bonjour


In [446]:
with open('fichier.txt','w') as f:
    for i in range(10):
        f.write("{}^2= {}\n".format(i,i**2))

In [447]:
#correction dictionnaire Carrés
carres_pairs={str(k):k**2 for k in range(0,20)}

In [448]:
random.seed(0)
print(random.random())

0.8444218515250481


In [449]:
print(random.randint(5,10))

8


In [450]:
print(random.randrange(100))

5


In [451]:
print(random.sample(range(100),10))

[33, 65, 62, 51, 38, 61, 45, 74, 27, 64]


In [452]:
print(random.sample(range(100),random.randrange(10)))

[36, 17]


In [453]:
random.shuffle(prenoms)

In [454]:
os.getcwd ##operationg system

<function nt.getcwd()>

In [455]:
filenames= glob.glob("*.txt")
d={}
for file in filenames:
    with open(file,'r') as f:
        d[file]=f.read().splitlines()
print(d)

{'fichier.txt': ['0^2= 0', '1^2= 1', '2^2= 4', '3^2= 9', '4^2= 16', '5^2= 25', '6^2= 36', '7^2= 49', '8^2= 64', '9^2= 81']}


In [456]:
with open('fichier.txt','r') as f:
    liste=f.read().splitlines()
liste

['0^2= 0',
 '1^2= 1',
 '2^2= 4',
 '3^2= 9',
 '4^2= 16',
 '5^2= 25',
 '6^2= 36',
 '7^2= 49',
 '8^2= 64',
 '9^2= 81']

In [457]:
liste=[line.strip() for line in open('fichier.txt','r')]
liste

['0^2= 0',
 '1^2= 1',
 '2^2= 4',
 '3^2= 9',
 '4^2= 16',
 '5^2= 25',
 '6^2= 36',
 '7^2= 49',
 '8^2= 64',
 '9^2= 81']

NUMPY

In [471]:
A=np.array([1,2,3])
A=A.reshape((A.shape[0],1))
##pour annuler le 1 dans le shape, A=A.squeezee()

In [472]:
A.shape

(3, 1)

In [460]:
B=np.zeros((3,))
type(B.shape)

tuple

In [461]:
C=np.ones((3,4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [462]:
##randn les nombres déterminés par random sont distribués selon la distribution normale
##seed fixe les nombres choisis
np.random.seed(0)
np.random.randn(3,4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [463]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [464]:
##20 points allant de 0 à 10
np.linspace(0,10,20,dtype=np.float16)
##nombres de 0 à 34 avec un pas de 3
np.arange(0,34,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [465]:
##on concatenne deux matrices
D=np.hstack((A,B))
D

array([1., 2., 3., 0., 0., 0.])

In [466]:
E=np.vstack((A,B))
E

array([[1., 2., 3.],
       [0., 0., 0.]])

In [469]:
##même résultat que vstack (axis=0) et hstack(axis=1), et permet de travailler en 3 dimenssions
F=np.concatenate((A,B),axis=0)
##remaniement matrices
F=F.reshape((3,2))
F

array([[1., 2.],
       [3., 0.],
       [0., 0.]])

In [476]:
#applatir tableau à une seule dimenssion
F.ravel().shape

(6,)

In [477]:
#m nombre de lignes
#n nombre de colonnes
#retourne une matrice aléatoire (m,n+1)
#avec une colonne biais (remplie de "1") tout à droite
def initialisation(m,n):

    return